name: Build iOS App

on:
  push:
    branches:
      - main  # Adjust if you are using a different default branch

jobs:
  build:
    runs-on: macos-latest  # Use a macOS runner for iOS builds

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0'  # Use the Flutter version you need

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS app
      run: flutter build ios --release

    - name: Archive iOS app
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration AppStoreDistribution archive -archivePath ${{ github.workspace }}/build/Runner.xcarchive

    - name: Export .ipa file
      run: |
        xcodebuild -exportArchive -archivePath ${{ github.workspace }}/build/Runner.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath ${{ github.workspace }}/build

    - name: Upload .ipa
      uses: actions/upload-artifact@v3
      with:
        name: ios-app
        path: build/Runner.ipa
